name: publish

on:
    release:
      types: [published]

jobs:
    build:
        name: Make SDist and weel
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install build
              run: pip install build

            - name: Building
              run: python -m build

            - uses: actions/upload-artifact@v3
              with:
                path: dist/*

    upload_on_pypi:
        needs: [build]
        runs-on: ubuntu-latest
        environment: testpypi
        permissions:
            id-token: write
        steps:
            - uses: actions/download-artifact@v3
              with:
                name: artifact
                path: dist

            - uses: pypa/gh-action-pypi-publish@release/v1
              with:
                repository-url: https://test.pypi.org/legacy/
                # password: ${{ secrets.TEST_PYPI_TOKEN }} # If you use a token
